# Generated by Django 5.2.7 on 2025-12-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id', 'stage', 'intention_key', 'step_in_intention']},
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_followups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='answer',
            name='coach_tone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='intention_key',
            field=models.CharField(blank=True, db_index=True, help_text="Logical group like 'origin_story' or 'brand_promise'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_core',
            field=models.BooleanField(default=False, help_text='If True, this question is core and requires stronger validation'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_chars',
            field=models.PositiveIntegerField(default=0, help_text='Minimum characters required for acceptable answer (0 = no-enforced min)'),
        ),
        migrations.AddField(
            model_name='question',
            name='step_in_intention',
            field=models.PositiveSmallIntegerField(default=1, help_text='Sequence position inside the intention group'),
        ),
    ]
