# Generated by Django 5.2.7 on 2025-12-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0002_alter_question_options_answer_ai_followups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ai_followups',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='coach_tone',
        ),
        migrations.RemoveField(
            model_name='question',
            name='intention_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_core',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_chars',
        ),
        migrations.RemoveField(
            model_name='question',
            name='step_in_intention',
        ),
    ]
