# Generated by Django 5.2.7 on 2025-12-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_alter_question_options_remove_answer_ai_followups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='followup_templates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='intention_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='min_chars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='step_in_intention',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='tone_hint',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
