# Generated by Django 5.2.7 on 2025-12-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0004_question_followup_templates_question_intention_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('welcome', 'Welcome & Setup'), ('structured_intake', 'Structured Intake'), ('refinement', 'Refinement Chat'), ('manifesto_review', 'Manifesto Review'), ('post_manifesto', 'Post-Manifesto Coaching')], default='welcome', max_length=20)),
                ('pending_followups', models.JSONField(blank=True, default=list, help_text='Queue of follow-up questions to ask')),
                ('off_topic_count', models.IntegerField(default=0, help_text='Track how many times user went off-topic (for guardrails)')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question user is working on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_sessions.question')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='user_sessions.session')),
            ],
            options={
                'verbose_name_plural': 'Conversation States',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('david_question', 'David Question'), ('user_answer', 'User Answer'), ('david_coaching', 'David Coaching'), ('david_followup', 'David Follow-up'), ('david_clarifier', 'David Clarifier'), ('david_celebration', 'David Celebration'), ('system_message', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('tone_tag', models.CharField(blank=True, choices=[('motivational', 'Motivational'), ('challenging', 'Challenging'), ('empathetic', 'Empathetic'), ('guiding', 'Guiding'), ('tough_love', 'Tough Love'), ('celebratory', 'Celebratory'), ('provocative', 'Provocative')], max_length=20, null=True)),
                ('is_from_ai', models.BooleanField(default=False)),
                ('requires_response', models.BooleanField(default=True, help_text='Does David expect an answer?')),
                ('is_resolved', models.BooleanField(default=False, help_text='User responded to this message')),
                ('suggested_improvement', models.TextField(blank=True, help_text="AI-suggested better version of user's answer", null=True)),
                ('order', models.IntegerField(default=0, help_text='Display sequence in chat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, help_text='Links to canonical Answer if user response was saved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_sessions.answer')),
                ('parent_message', models.ForeignKey(blank=True, help_text='For threading follow-up questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_sessions.conversationmessage')),
                ('question', models.ForeignKey(blank=True, help_text='Links to canonical Question if this is a structured question', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_sessions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='user_sessions.session')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['session', 'order'], name='user_sessio_session_e692b8_idx'), models.Index(fields=['session', 'is_resolved'], name='user_sessio_session_32d389_idx')],
            },
        ),
    ]
