# Generated by Django 5.2.7 on 2025-12-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0005_conversationstate_conversationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationstate',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='followup_templates',
        ),
        migrations.RemoveField(
            model_name='question',
            name='intention_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_core',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_chars',
        ),
        migrations.RemoveField(
            model_name='question',
            name='step_in_intention',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tone_hint',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
        migrations.DeleteModel(
            name='ConversationState',
        ),
    ]
