# Generated by Django 4.2.27 on 2026-02-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0007_alter_answer_question_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Foundation'), (2, 'Identity')], default=1),
        ),
    ]
