# Generated by Django 4.2.28 on 2026-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0009_foundationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Foundation'), (3, 'Identity'), (4, 'More')], default=1),
        ),
    ]
