# Generated by Django 4.2.27 on 2026-05-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0018_airequesttrace_confidence_reasoning'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airequesttrace',
            new_name='user_sessio_created_079c31_idx',
            old_name='user_sessio_created_a7f1c2_idx',
        ),
        migrations.RenameIndex(
            model_name='airequesttrace',
            new_name='user_sessio_agent_i_72b22e_idx',
            old_name='user_sessio_agent_i_8b3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='user_sessio_user_id_f12917_idx',
            old_name='user_sessio_user_ai_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationresult',
            new_name='user_sessio_run_id_9bbc62_idx',
            old_name='user_sessio_run_id_8f3a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='ragquerylog',
            new_name='user_sessio_created_276e90_idx',
            old_name='user_sessio_created_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='ragquerylog',
            new_name='user_sessio_user_id_31658b_idx',
            old_name='user_sessio_user_id_9d2e3f_idx',
        ),
    ]
