# Generated by Django 4.2.27 on 2026-06-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0020_question_ai_refinement_cache'),
        ('user_sessions', '0023_aituningversion'),
    ]

    operations = [
    ]
