# Generated by Django 4.2.27 on 2026-06-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0025_ragdevconfig_phase1_base_and_injection_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aituningversion',
            new_name='user_sessio_section_639858_idx',
            old_name='user_sessio_section_3f5964_idx',
        ),
        migrations.RenameIndex(
            model_name='aituningversion',
            new_name='user_sessio_is_defa_e8a41c_idx',
            old_name='user_sessio_is_defa_54ab5f_idx',
        ),
        migrations.RenameIndex(
            model_name='ragphaseartifact',
            new_name='user_sessio_session_a01ad8_idx',
            old_name='user_sessions_ragphase_session_322ca2_idx',
        ),
    ]
