# Generated by Django 4.2.27 on 2026-07-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0027_orbturnauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_user_em_61e573_idx',
            old_name='user_sessio_user_em_83f8bb_idx',
        ),
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_user_id_fadb2c_idx',
            old_name='user_sessio_user_id_3e7f45_idx',
        ),
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_session_cd7d91_idx',
            old_name='user_sessio_session_18042a_idx',
        ),
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_questio_3e3e5b_idx',
            old_name='user_sessio_questio_3d82b8_idx',
        ),
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_associa_13ae55_idx',
            old_name='user_sessio_assoc__d3077e_idx',
        ),
        migrations.RenameIndex(
            model_name='orbturnauditlog',
            new_name='user_sessio_status_18aff9_idx',
            old_name='user_sessio_status_86f8fe_idx',
        ),
    ]
