# Generated by GitHub Copilot on 2026-06-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_agency_approved_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("one_time", "One time"), ("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        max_length=20,
                    ),
                ),
                ("stripe_product_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If empty, checkout uses the price configured here.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription plan",
                "verbose_name_plural": "Subscription plans",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("stripe_checkout_session_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("stripe_payment_intent_id", models.CharField(blank=True, max_length=255)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to="accounts.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User subscription",
                "verbose_name_plural": "User subscriptions",
                "ordering": ["-updated_at"],
            },
        ),
    ]
